spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hmDatabase?serverTimezone=Asia/Seoul
    username: root
    password: 71040525
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache : false
    cache-ttl : 3600

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

