spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hmproject?serverTimezone=Asia/Seoul
    username: man
    password: dpsjwl!@34
    #url: jdbc:mariadb://34.64.198.131:3306/hmproject?useUnicode=true&characterEncoding=utf8mb4
    #username: man
    #password: dpsjwl!@34
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache : false
    cache-ttl : 3600
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.HmProject.Community.domain
jwt:
  header: Authorization
  secret: r6LGxQo79ytq5FKHrZoQK4hpMLicpcYzUNkdz3btmEY=
  token-validity-in-seconds: 1800
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: info

