spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/hmDatabase?serverTimezone=Asia/Seoul
    #username: root
    #password: 71040525
    url: jdbc:mariadb://localhost:3306/spring_mvc_project?useUnicode=true&characterEncoding=utf8mb4
    username: hwayoung
    password: hwayoung123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache : false
    cache-ttl : 3600
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.HmProject.Community.domain

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: info

